/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.AppController;
import java.awt.List;
import view.client.HomePanel;

/**
 *
 * @author estifanos
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    private MainFrame mainFrame;
    private AppController controller;
    /**
     * Creates new form SignUpPanel
     * @param mainFrame
     */
    public LoginPanel(MainFrame mainFrame, AppController controller) {
        initComponents();
        this.mainFrame = mainFrame;
        this.controller = controller;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        signupText = new javax.swing.JLabel();
        signupButton = new javax.swing.JButton();
        accountField = new javax.swing.JTextField();
        loginText = new javax.swing.JTextPane();
        passwordField = new javax.swing.JPasswordField();
        errorLabel = new javax.swing.JLabel();

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setEnabled(false);
        jPanel1.setFocusable(false);

        loginButton.setBackground(new java.awt.Color(0, 0, 0));
        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setPreferredSize(new java.awt.Dimension(73, 26));
        loginButton.addActionListener(this::loginButtonActionPerformed);

        signupText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signupText.setText("Don't have an account?");

        signupButton.setBackground(new java.awt.Color(242, 242, 242));
        signupButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signupButton.setForeground(new java.awt.Color(0, 153, 255));
        signupButton.setText("Sign up here.");
        signupButton.setBorder(null);
        signupButton.setIconTextGap(0);
        signupButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        signupButton.addActionListener(this::signupButtonActionPerformed);

        accountField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accountField.setText("Username");
        accountField.setToolTipText("Enter your username here.");
        accountField.setMaximumSize(new java.awt.Dimension(80, 30));
        accountField.setName("Account"); // NOI18N
        accountField.setPreferredSize(new java.awt.Dimension(73, 26));
        accountField.addActionListener(this::accountFieldActionPerformed);

        loginText.setEditable(false);
        loginText.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        loginText.setText("Login as a client or admin to start using features.");
        loginText.setFocusable(false);
        loginText.setOpaque(false);

        passwordField.setText("Password");
        passwordField.setToolTipText("Enter your password here.");

        errorLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(204, 0, 51));
        errorLabel.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(errorLabel)
                            .addComponent(accountField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordField)
                            .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginText, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(signupText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signupButton)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupText)
                    .addComponent(signupButton))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {accountField, passwordField});

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void accountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountFieldActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        // TODO add your handling code here:
        this.mainFrame.showScreen(new SignUpPanel(mainFrame, this.controller));
    }//GEN-LAST:event_signupButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String status = this.controller.checkLoginDetails(
                this.accountField.getText().trim(), 
                new String(passwordField.getPassword()));
        if (status == "success") {
            this.mainFrame.showScreen(new HomePanel(mainFrame, this.controller));
        } else {
            showError(status);
        }
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextPane loginText;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel signupText;
    // End of variables declaration//GEN-END:variables
    private void showError(String msg) {
        errorLabel.setText(msg);
    }

    

}
