/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.AppController;
import view.client.HomePanel;

/**
 *
 * @author estifanos
 */
public class SignUpPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private AppController controller;
    /**
     * Creates new form SignUpPanel
     */
    public SignUpPanel(MainFrame mainFrame, AppController controller) {
        initComponents();
        this.mainFrame = mainFrame;
        this.controller = controller;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        signupButton = new javax.swing.JButton();
        gtLogin = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        accountField = new javax.swing.JTextField();
        signupText = new javax.swing.JTextPane();
        jPasswordField1 = new javax.swing.JPasswordField();
        accountField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setEnabled(false);
        jPanel2.setFocusable(false);

        signupButton.setBackground(new java.awt.Color(0, 0, 0));
        signupButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signupButton.setForeground(new java.awt.Color(255, 255, 255));
        signupButton.setText("Sign up");
        signupButton.setPreferredSize(new java.awt.Dimension(73, 26));
        signupButton.addActionListener(this::signupButtonActionPerformed);

        gtLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gtLogin.setText("Already have an account?");

        loginButton.setBackground(new java.awt.Color(242, 242, 242));
        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(0, 153, 255));
        loginButton.setText("Log in here");
        loginButton.setBorder(null);
        loginButton.setIconTextGap(0);
        loginButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        loginButton.addActionListener(this::loginButtonActionPerformed);

        accountField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accountField.setText("Username");
        accountField.setToolTipText("Enter your username here.");
        accountField.setMaximumSize(new java.awt.Dimension(80, 30));
        accountField.setName("Account"); // NOI18N
        accountField.setPreferredSize(new java.awt.Dimension(73, 26));
        accountField.addActionListener(this::accountFieldActionPerformed);

        signupText.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        signupText.setText("Create an account as a client or an admin.");
        signupText.setFocusable(false);
        signupText.setOpaque(false);

        jPasswordField1.setText("Password");
        jPasswordField1.setToolTipText("Enter your password here.");

        accountField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accountField1.setText("Your name");
        accountField1.setToolTipText("Enter your username here.");
        accountField1.setMaximumSize(new java.awt.Dimension(80, 30));
        accountField1.setName("Account"); // NOI18N
        accountField1.setPreferredSize(new java.awt.Dimension(73, 26));
        accountField1.addActionListener(this::accountField1ActionPerformed);

        jComboBox1.setBackground(new java.awt.Color(248, 248, 248));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a Client", "an Admin" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("I am ");

        errorLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorLabel.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorLabel)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(signupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(signupText)
                                .addComponent(accountField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPasswordField1)
                                .addComponent(accountField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(gtLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginButton)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(signupText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(gtLogin))
                .addGap(94, 94, 94))
        );

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        // TODO add your handling code here:
        showError("Error");
        //this.mainFrame.showScreen(new HomePanel(mainFrame));
    }//GEN-LAST:event_signupButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        this.mainFrame.showScreen(new LoginPanel(mainFrame, this.controller));
    }//GEN-LAST:event_loginButtonActionPerformed

    private void accountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountFieldActionPerformed

    private void accountField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountField1ActionPerformed

    private void showError(String msg) {
        errorLabel.setText(msg);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountField;
    private javax.swing.JTextField accountField1;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel gtLogin;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton signupButton;
    private javax.swing.JTextPane signupText;
    // End of variables declaration//GEN-END:variables
}
