/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author estifanos
 */
public class TransactionPanel extends javax.swing.JPanel {

    /**
     * Creates new form Transaction
     */
    public TransactionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transactionStatus = new javax.swing.JLabel();
        transactionStatus1 = new javax.swing.JLabel();
        transactionStatus2 = new javax.swing.JLabel();
        transactionStatus3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        setMaximumSize(new java.awt.Dimension(32767, 50));
        setMinimumSize(new java.awt.Dimension(0, 50));

        transactionStatus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        transactionStatus.setText("STATUS");

        transactionStatus1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        transactionStatus1.setText("TYPE");

        transactionStatus2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        transactionStatus2.setText("AMOUNT");

        transactionStatus3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        transactionStatus3.setText("APPLICANT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transactionStatus3)
                .addGap(18, 18, 18)
                .addComponent(transactionStatus1)
                .addGap(18, 18, 18)
                .addComponent(transactionStatus2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(transactionStatus)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transactionStatus)
                    .addComponent(transactionStatus1)
                    .addComponent(transactionStatus2)
                    .addComponent(transactionStatus3))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel transactionStatus;
    private javax.swing.JLabel transactionStatus1;
    private javax.swing.JLabel transactionStatus2;
    private javax.swing.JLabel transactionStatus3;
    // End of variables declaration//GEN-END:variables
}
