/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.MainController;
import model.account.Transaction;
import model.users.Client;
import model.users.Role;
import model.users.User;
import view.admin.UserListPanel;

/**
 *
 * @author estifanos
 */
public class UserPanel extends javax.swing.JPanel {
    private MainController mainController;
    private MainFrame mainFrame;
    private User user;
    /**
     * Creates new form Transaction
     */
    public UserPanel(MainFrame mainFrame, MainController mainController, User user) {
        initComponents();
        this.mainFrame = mainFrame;
        this.mainController = mainController;
        this.user = user;
        if (user.getRole()==Role.ADMIN) {
            this.viewaccountButton.show(false);
        }
        this.usernameLabel.setText(user.getUsername());
        this.fullnameLabel.setText(user.getName());
        this.roleLabel.setText(user.getRoleAsString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullnameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        viewaccountButton = new javax.swing.JButton();
        roleLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        setMaximumSize(new java.awt.Dimension(32767, 60));
        setMinimumSize(new java.awt.Dimension(0, 60));

        fullnameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        fullnameLabel.setText("Full name");

        usernameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        usernameLabel.setText("Username");

        viewaccountButton.setBackground(new java.awt.Color(248, 248, 248));
        viewaccountButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        viewaccountButton.setText("View Account");
        viewaccountButton.addActionListener(this::viewaccountButtonActionPerformed);

        roleLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        roleLabel.setText("Role");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(usernameLabel)
                .addGap(18, 18, 18)
                .addComponent(fullnameLabel)
                .addGap(18, 18, 18)
                .addComponent(roleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(viewaccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullnameLabel)
                    .addComponent(usernameLabel)
                    .addComponent(viewaccountButton)
                    .addComponent(roleLabel))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewaccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewaccountButtonActionPerformed
        // TODO add your handling code here:
        this.mainFrame.showScreen(new UserListPanel(mainFrame, mainController, (Client) user));
    }//GEN-LAST:event_viewaccountButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fullnameLabel;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton viewaccountButton;
    // End of variables declaration//GEN-END:variables
}
