/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.client;

import controller.MainController;
import java.util.ArrayList;
import model.account.Transaction;
import model.account.TransactionStatus;
import model.users.Client;
import model.users.User;
import view.LoginPanel;
import view.MainFrame;
import view.Refreshable;
import view.TransactionPanel;

/**
 *
 * @author estifanos
 */
public class HomePanel extends javax.swing.JPanel implements Refreshable {
    private MainFrame mainFrame;
    private MainController mainController;
    private ArrayList<Transaction> transactionList;
    
    /**
     * Creates new form HomePanel
     */
    public HomePanel(MainFrame mainFrame, MainController mainController) {
        initComponents();
        this.mainFrame = mainFrame;
        this.mainController = mainController;
        
        Client currentUser = (Client) this.mainController.getCurrentUser();
        this.nameLabel.setText("Logged in as "+currentUser.getName()+" (Client)");
        this.accountBalanceLabel.setText(String.valueOf(currentUser.getAccount().getBalance()));
        this.creditScoreLabel.setText(String.valueOf(currentUser.getAccount().getCreditScore()));
        
        this.transactionList = currentUser.getAccount().getTransactions();        
        refreshTransactionPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        balanceInfo = new javax.swing.JPanel();
        balanceLabel = new javax.swing.JLabel();
        accountBalanceLabel = new javax.swing.JLabel();
        depositButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        creditInfo = new javax.swing.JPanel();
        scoreLabel = new javax.swing.JLabel();
        creditScoreLabel = new javax.swing.JLabel();
        loanButton = new javax.swing.JButton();
        tabPanel = new javax.swing.JTabbedPane();
        pendingPanel = new javax.swing.JScrollPane();
        pendingContainer = new javax.swing.JPanel();
        historyPanel = new javax.swing.JScrollPane();
        historyContainer = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 500));

        jPanel4.setBackground(new java.awt.Color(248, 248, 248));

        balanceInfo.setBackground(new java.awt.Color(255, 255, 255));

        balanceLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        balanceLabel.setText("Account Balance");

        accountBalanceLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        accountBalanceLabel.setText("$ 26,728.42");

        depositButton.setBackground(new java.awt.Color(248, 248, 248));
        depositButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        depositButton.setText("Deposit");
        depositButton.addActionListener(this::depositButtonActionPerformed);

        withdrawButton.setBackground(new java.awt.Color(248, 248, 248));
        withdrawButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        withdrawButton.setText("Withdraw");
        withdrawButton.addActionListener(this::withdrawButtonActionPerformed);

        javax.swing.GroupLayout balanceInfoLayout = new javax.swing.GroupLayout(balanceInfo);
        balanceInfo.setLayout(balanceInfoLayout);
        balanceInfoLayout.setHorizontalGroup(
            balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceInfoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(balanceInfoLayout.createSequentialGroup()
                        .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(accountBalanceLabel)
                    .addComponent(balanceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        balanceInfoLayout.setVerticalGroup(
            balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceInfoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(accountBalanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        nameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        nameLabel.setText("Logged in as Mohammed M. (Client)");

        creditInfo.setBackground(new java.awt.Color(255, 255, 255));

        scoreLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        scoreLabel.setText("Credit Score");

        creditScoreLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        creditScoreLabel.setText("728");

        loanButton.setBackground(new java.awt.Color(248, 248, 248));
        loanButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        loanButton.setText("Take a Loan");
        loanButton.addActionListener(this::loanButtonActionPerformed);

        javax.swing.GroupLayout creditInfoLayout = new javax.swing.GroupLayout(creditInfo);
        creditInfo.setLayout(creditInfoLayout);
        creditInfoLayout.setHorizontalGroup(
            creditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditInfoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(creditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditScoreLabel)
                    .addComponent(scoreLabel))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        creditInfoLayout.setVerticalGroup(
            creditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditInfoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(creditScoreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(loanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        tabPanel.setBackground(new java.awt.Color(255, 255, 255));
        tabPanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pendingContainer.setBackground(new java.awt.Color(255, 255, 255));
        pendingContainer.setLayout(new javax.swing.BoxLayout(pendingContainer, javax.swing.BoxLayout.Y_AXIS));
        pendingPanel.setViewportView(pendingContainer);

        tabPanel.addTab("Pending Transactions", pendingPanel);

        historyContainer.setBackground(new java.awt.Color(255, 255, 255));
        historyContainer.setLayout(new javax.swing.BoxLayout(historyContainer, javax.swing.BoxLayout.Y_AXIS));
        historyPanel.setViewportView(historyContainer);

        tabPanel.addTab("Transaction History", historyPanel);

        logoutButton.setBackground(new java.awt.Color(204, 0, 0));
        logoutButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log out");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(balanceInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(creditInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(72, 72, 72))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(nameLabel)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        mainController.getAuthController().Logout();
        this.mainFrame.showScreen(new LoginPanel(mainFrame, mainController));
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
        this.mainFrame.showScreen(new DepositPanel(mainFrame, mainController));
    }//GEN-LAST:event_depositButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        // TODO add your handling code here:
        this.mainFrame.showScreen(new WithdrawPanel(mainFrame, mainController));
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void loanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanButtonActionPerformed
        // TODO add your handling code here:
//        this.mainController.validateTransaction("New transaction");
//        this.TransactionList.add("New transaction");
        refreshTransactionPanel();
        this.mainFrame.showScreen(new LoanPanel(mainFrame, mainController));
    }//GEN-LAST:event_loanButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBalanceLabel;
    private javax.swing.JPanel balanceInfo;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JPanel creditInfo;
    private javax.swing.JLabel creditScoreLabel;
    private javax.swing.JButton depositButton;
    private javax.swing.JPanel historyContainer;
    private javax.swing.JScrollPane historyPanel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton loanButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel pendingContainer;
    private javax.swing.JScrollPane pendingPanel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JButton withdrawButton;
    // End of variables declaration//GEN-END:variables
    @Override
    public void refreshUI() {
        this.mainFrame.showScreen(new HomePanel(mainFrame, mainController));
        refreshTransactionPanel();
    }
    
    private void refreshTransactionPanel() {
        pendingContainer.removeAll();
        if (this.transactionList == null) {return;}
        for (Transaction t : this.transactionList) {
            if (t.getStatus() == TransactionStatus.PENDING) { pendingContainer.add(new TransactionPanel(t, this.mainController, this)); }
            else { historyContainer.add(new TransactionPanel(t, this.mainController, this)); }
        }

        pendingContainer.revalidate();
        pendingContainer.repaint();
//        JScrollBar bar = scrollPane.getVerticalScrollBar();
//        bar.setValue(bar.getMaximum());
    }
}
