/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.client;

import controller.MainController;
import model.exceptions.EmptyFieldException;
import model.exceptions.LowCreditScoreException;
import model.exceptions.UnpaidLoanException;
import model.users.Client;
import view.LoginPanel;
import view.MainFrame;

/**
 *
 * @author estifanos
 */
public class LoanPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private MainController mainController;
    /**
     * Creates new form LoanPanel
     */
    public LoanPanel(MainFrame mainFrame, MainController mainController) {
        initComponents();
        
        this.mainFrame = mainFrame;
        this.mainController = mainController;
        Client currentUser = (Client) this.mainController.getCurrentUser();
        this.nameLabel.setText("Logged in as "+currentUser.getName()+" (Client)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        balanceInfo = new javax.swing.JPanel();
        loanLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        loanField = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(248, 248, 248));

        balanceInfo.setBackground(new java.awt.Color(255, 255, 255));

        loanLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        loanLabel.setText("Apply for a Loan");

        submitButton.setBackground(new java.awt.Color(248, 248, 248));
        submitButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        submitButton.setText("Submit Application");
        submitButton.addActionListener(this::submitButtonActionPerformed);

        loanField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loanField.setText("Amount");
        loanField.addActionListener(this::loanFieldActionPerformed);

        errorLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(204, 0, 51));
        errorLabel.setText(" ");

        javax.swing.GroupLayout balanceInfoLayout = new javax.swing.GroupLayout(balanceInfo);
        balanceInfo.setLayout(balanceInfoLayout);
        balanceInfoLayout.setHorizontalGroup(
            balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceInfoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorLabel)
                    .addGroup(balanceInfoLayout.createSequentialGroup()
                        .addComponent(loanField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loanLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        balanceInfoLayout.setVerticalGroup(
            balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceInfoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(loanLabel)
                .addGap(18, 18, 18)
                .addGroup(balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLabel)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        nameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        nameLabel.setText("Logged in as Mohammed M. (Client)");

        logoutButton.setBackground(new java.awt.Color(204, 0, 0));
        logoutButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log out");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        HomeButton.setBackground(new java.awt.Color(248, 248, 248));
        HomeButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        HomeButton.setText("Home");
        HomeButton.addActionListener(this::HomeButtonActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(balanceInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 509, Short.MAX_VALUE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(72, 72, 72))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(balanceInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        mainController.getAuthController().Logout();
        this.mainFrame.showScreen(new LoginPanel(mainFrame, mainController));
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        this.mainFrame.showScreen(new HomePanel(mainFrame, this.mainController));
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            this.mainController.getClientController().requestLoan((Client) this.mainController.getCurrentUser(), this.loanField.getText().trim());
            this.mainFrame.showScreen(new HomePanel(mainFrame, this.mainController));
        } catch (NumberFormatException e) {
            errorLabel.setText("Please enter a valid number amount.");
        } catch (EmptyFieldException e) {
            errorLabel.setText("No empty fields allowed.");
        } catch (LowCreditScoreException ex) {
            errorLabel.setText("Credit is too low to borrow that amount.");
        } catch (UnpaidLoanException ex) {
            errorLabel.setText("Settle outstanding loan before applying for a new one.");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void loanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeButton;
    private javax.swing.JPanel balanceInfo;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField loanField;
    private javax.swing.JLabel loanLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
