/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.client;

import controller.MainController;
import model.exceptions.EmptyFieldException;
import model.exceptions.InsufficientFundsException;
import model.users.Client;
import view.LoginPanel;
import view.MainFrame;

/**
 *
 * @author estifanos
 */
public class WithdrawPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private MainController mainController;
    /**
     * Creates new form WithdrawlPanel
     */
    public WithdrawPanel(MainFrame mainFrame, MainController mainController) {
        initComponents();
        
        this.mainFrame = mainFrame;
        this.mainController = mainController;
        Client currentUser = (Client) this.mainController.getCurrentUser();
        this.nameLabel.setText("Logged in as "+currentUser.getName()+" (Client)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        balanceInfo = new javax.swing.JPanel();
        withdrawLabel = new javax.swing.JLabel();
        withdrawButton = new javax.swing.JButton();
        withdrawalField = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(248, 248, 248));

        balanceInfo.setBackground(new java.awt.Color(255, 255, 255));

        withdrawLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        withdrawLabel.setText("Withdraw from Account");

        withdrawButton.setBackground(new java.awt.Color(248, 248, 248));
        withdrawButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        withdrawButton.setText("Confirm withdraw");
        withdrawButton.addActionListener(this::withdrawButtonActionPerformed);

        withdrawalField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        withdrawalField.setText("Amount");
        withdrawalField.addActionListener(this::withdrawalFieldActionPerformed);

        errorLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(204, 0, 51));
        errorLabel.setText(" ");

        javax.swing.GroupLayout balanceInfoLayout = new javax.swing.GroupLayout(balanceInfo);
        balanceInfo.setLayout(balanceInfoLayout);
        balanceInfoLayout.setHorizontalGroup(
            balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceInfoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorLabel)
                    .addComponent(withdrawLabel)
                    .addGroup(balanceInfoLayout.createSequentialGroup()
                        .addComponent(withdrawalField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        balanceInfoLayout.setVerticalGroup(
            balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceInfoLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(withdrawLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(withdrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withdrawalField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(errorLabel))
        );

        nameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        nameLabel.setText("Logged in as Mohammed M. (Client)");

        logoutButton.setBackground(new java.awt.Color(204, 0, 0));
        logoutButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log out");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        HomeButton.setBackground(new java.awt.Color(248, 248, 248));
        HomeButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        HomeButton.setText("Home");
        HomeButton.addActionListener(this::HomeButtonActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(balanceInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(balanceInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        mainController.getAuthController().Logout();
        this.mainFrame.showScreen(new LoginPanel(mainFrame, mainController));
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void withdrawalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawalFieldActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        this.mainFrame.showScreen(new HomePanel(mainFrame, this.mainController));
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        // TODO add your handling code here:
        try {
            this.mainController.getClientController().withdraw((Client) this.mainController.getCurrentUser(), this.withdrawalField.getText().trim());
            this.mainFrame.showScreen(new HomePanel(mainFrame, this.mainController));
        } catch (NumberFormatException e) {
            errorLabel.setText("Please enter a valid number amount.");
        } catch (EmptyFieldException e) {
            errorLabel.setText("No empty fields allowed.");
        } catch (InsufficientFundsException e) {
            errorLabel.setText("Insufficient funds for withdrawal.");
        }
    }//GEN-LAST:event_withdrawButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeButton;
    private javax.swing.JPanel balanceInfo;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton withdrawButton;
    private javax.swing.JLabel withdrawLabel;
    private javax.swing.JTextField withdrawalField;
    // End of variables declaration//GEN-END:variables
}
