/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;

import controller.MainController;
import java.util.ArrayList;
import model.account.Transaction;
import model.account.TransactionStatus;
import model.users.Admin;
import model.users.Client;
import view.LoginPanel;
import view.MainFrame;
import view.Refreshable;
import view.TransactionPanel;

/**
 *
 * @author estifanos
 */
public class HomePanel extends javax.swing.JPanel implements Refreshable {
    private MainFrame mainFrame;
    private MainController mainController;
    private ArrayList<Transaction> transactionList;
    
    /**
     * Creates new form HomePanel
     */
    public HomePanel(MainFrame mainFrame, MainController mainController) {
        initComponents();
        
        this.mainFrame = mainFrame;
        this.mainController = mainController;
        
        Admin currentUser = (Admin) this.mainController.getCurrentUser();
        this.nameLabel.setText("Logged in as "+currentUser.getName()+" (Admin)");
        this.transactionList = this.mainController.getAdminController().getAllTransactions();        
        refreshUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        activityTabs = new javax.swing.JTabbedPane();
        pendingPanel = new javax.swing.JScrollPane();
        pendingContainer = new javax.swing.JPanel();
        historyPanel = new javax.swing.JScrollPane();
        historyContainer = new javax.swing.JPanel();

        jPanel4.setBackground(new java.awt.Color(248, 248, 248));

        logoutButton.setBackground(new java.awt.Color(204, 0, 0));
        logoutButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log out");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        nameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        nameLabel.setText("Logged in as Akrem K. (Admin)");

        searchField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchField.setText("Search for an Account");

        searchButton.setBackground(new java.awt.Color(248, 248, 248));
        searchButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(this::searchButtonActionPerformed);

        activityTabs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pendingContainer.setBackground(new java.awt.Color(255, 255, 255));
        pendingContainer.setLayout(new javax.swing.BoxLayout(pendingContainer, javax.swing.BoxLayout.Y_AXIS));
        pendingPanel.setViewportView(pendingContainer);

        activityTabs.addTab("Pending Transactions", pendingPanel);

        historyContainer.setBackground(new java.awt.Color(255, 255, 255));
        historyContainer.setLayout(new javax.swing.BoxLayout(historyContainer, javax.swing.BoxLayout.Y_AXIS));
        historyPanel.setViewportView(historyContainer);

        activityTabs.addTab("Transaction History", historyPanel);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(activityTabs, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(searchField)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(nameLabel)
                .addGap(41, 41, 41)
                .addComponent(activityTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        mainController.getAuthController().Logout();
        this.mainFrame.showScreen(new LoginPanel(mainFrame, mainController));

    }//GEN-LAST:event_logoutButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (searchField.getText().trim().length() > 0) {
            this.mainFrame.showScreen(new SearchResultsPanel(mainFrame, this.mainController, searchField.getText().trim()));
        }
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane activityTabs;
    private javax.swing.JPanel historyContainer;
    private javax.swing.JScrollPane historyPanel;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel pendingContainer;
    private javax.swing.JScrollPane pendingPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
    @Override
    public void refreshUI() {
        refreshTransactionPanel();
    }
        
    public void refreshTransactionPanel() {
        pendingContainer.removeAll();
        if (this.transactionList == null) {return;}
        for (Transaction t : this.transactionList) {
            if (t.getStatus() == TransactionStatus.PENDING) { pendingContainer.add(new TransactionPanel(t, this.mainController, this)); }
            else { historyContainer.add(new TransactionPanel(t, this.mainController, this)); }
        }

        pendingContainer.revalidate();
        pendingContainer.repaint();
//        JScrollBar bar = scrollPane.getVerticalScrollBar();
//        bar.setValue(bar.getMaximum());
    }

}
