/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;

import controller.MainController;
import model.users.Admin;
import model.account.Transaction;
import model.users.Client;
import view.LoginPanel;
import view.MainFrame;
import java.util.ArrayList;
import model.account.TransactionStatus;
import view.Refreshable;
import view.TransactionPanel;

public class UserListPanel extends javax.swing.JPanel implements Refreshable {
    private MainFrame mainFrame;
    private MainController mainController;
    private ArrayList<Transaction> transactionList;
    
    public UserListPanel(MainFrame mainFrame, MainController mainController, Client client) {
        initComponents();
        this.mainFrame = mainFrame;
        this.mainController = mainController;
        
        Admin currentUser = (Admin) this.mainController.getCurrentUser();
        this.nameLabel.setText("Logged in as "+currentUser.getName()+" (Admin)");
        this.activityLabel.setText("Viewing account: "+client.getName());
        this.accountBalanceLabel.setText(String.valueOf(client.getAccount().getBalance()));
        this.creditScoreLabel.setText(String.valueOf(client.getAccount().getCreditScore()));
        
        this.transactionList = client.getAccount().getTransactions();    
        refreshUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        balanceInfo = new javax.swing.JPanel();
        balanceLabel = new javax.swing.JLabel();
        accountBalanceLabel = new javax.swing.JLabel();
        activityLabel = new javax.swing.JLabel();
        creditInfo = new javax.swing.JPanel();
        scoreLabel = new javax.swing.JLabel();
        creditScoreLabel = new javax.swing.JLabel();
        tabPanel = new javax.swing.JTabbedPane();
        pendingPanel = new javax.swing.JScrollPane();
        pendingContainer = new javax.swing.JPanel();
        historyPanel = new javax.swing.JScrollPane();
        historyContainer = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(248, 248, 248));

        balanceInfo.setBackground(new java.awt.Color(255, 255, 255));

        balanceLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        balanceLabel.setText("Account Balance");

        accountBalanceLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        accountBalanceLabel.setText("$ 26,728.42");

        javax.swing.GroupLayout balanceInfoLayout = new javax.swing.GroupLayout(balanceInfo);
        balanceInfo.setLayout(balanceInfoLayout);
        balanceInfoLayout.setHorizontalGroup(
            balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceInfoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountBalanceLabel)
                    .addComponent(balanceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        balanceInfoLayout.setVerticalGroup(
            balanceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceInfoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(accountBalanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balanceLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        activityLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        activityLabel.setText("Viewing Mohammed M.");

        creditInfo.setBackground(new java.awt.Color(255, 255, 255));

        scoreLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        scoreLabel.setText("Credit Score");

        creditScoreLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        creditScoreLabel.setText("728");

        javax.swing.GroupLayout creditInfoLayout = new javax.swing.GroupLayout(creditInfo);
        creditInfo.setLayout(creditInfoLayout);
        creditInfoLayout.setHorizontalGroup(
            creditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditInfoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(creditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creditScoreLabel)
                    .addComponent(scoreLabel))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        creditInfoLayout.setVerticalGroup(
            creditInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditInfoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(creditScoreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreLabel)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        tabPanel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pendingContainer.setBackground(new java.awt.Color(255, 255, 255));
        pendingContainer.setLayout(new javax.swing.BoxLayout(pendingContainer, javax.swing.BoxLayout.Y_AXIS));
        pendingPanel.setViewportView(pendingContainer);

        tabPanel.addTab("Pending Transactions", pendingPanel);

        historyContainer.setBackground(new java.awt.Color(255, 255, 255));
        historyContainer.setLayout(new javax.swing.BoxLayout(historyContainer, javax.swing.BoxLayout.Y_AXIS));
        historyPanel.setViewportView(historyContainer);

        tabPanel.addTab("Transaction History", historyPanel);

        logoutButton.setBackground(new java.awt.Color(204, 0, 0));
        logoutButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log out");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        nameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        nameLabel.setText("Logged in as Akrem K. (Admin)");

        searchField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchField.setText("Search for an Account");

        searchButton.setBackground(new java.awt.Color(248, 248, 248));
        searchButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(this::searchButtonActionPerformed);

        homeButton.setBackground(new java.awt.Color(248, 248, 248));
        homeButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        homeButton.setText("Home");
        homeButton.addActionListener(this::homeButtonActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabPanel)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(balanceInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(creditInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nameLabel)
                        .addComponent(activityLabel, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activityLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(creditInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(balanceInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(tabPanel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        mainController.getAuthController().Logout();
        this.mainFrame.showScreen(new LoginPanel(mainFrame, mainController));
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (searchField.getText().trim().length() > 0) {
            this.mainFrame.showScreen(new SearchResultsPanel(mainFrame, this.mainController, searchField.getText().trim()));
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        this.mainFrame.showScreen(new HomePanel(mainFrame, this.mainController));
    }//GEN-LAST:event_homeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBalanceLabel;
    private javax.swing.JLabel activityLabel;
    private javax.swing.JPanel balanceInfo;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JPanel creditInfo;
    private javax.swing.JLabel creditScoreLabel;
    private javax.swing.JPanel historyContainer;
    private javax.swing.JScrollPane historyPanel;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel pendingContainer;
    private javax.swing.JScrollPane pendingPanel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables
    @Override
    public void refreshUI() {
        refreshTransactionPanel();
    }
    
    public void refreshTransactionPanel() {
        pendingContainer.removeAll();
        if (this.transactionList == null) {return;}
        for (Transaction t : this.transactionList) {
            if (t.getStatus() == TransactionStatus.PENDING) { pendingContainer.add(new TransactionPanel(t, this.mainController, this)); }
            else { historyContainer.add(new TransactionPanel(t, this.mainController, this)); }
        }

        pendingContainer.revalidate();
        pendingContainer.repaint();
//        JScrollBar bar = scrollPane.getVerticalScrollBar();
//        bar.setValue(bar.getMaximum());
    }

}
